[project]
name = "gpu-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpustat>=1.1.1",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
]
